# Generated by Django 5.2.9 on 2025-12-31 02:09

import django.db.models.deletion
import medical.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cin', medical.models.EncryptedCharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('insurance_type', models.CharField(choices=[('AMO', 'AMO (CNSS/CNOPS)'), ('MUTUELLE', 'Mutuelle Privée'), ('NONE', 'Sans Assurance')], default='NONE', max_length=20)),
                ('insurance_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Description', models.TextField(blank=True)),
                ('Status', models.CharField(default='Scheduled', max_length=50)),
                ('CategoryColor', models.CharField(default='#0077BE', max_length=7)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ToothFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('surface', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
    ]
