# Generated by Django 5.2.9 on 2026-01-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tooth_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
