# Generated by Django 5.2.9 on 2026-01-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_appointment_tooth_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(max_length=2)),
                ('step_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('cleaning', 'Cleaning'), ('filling', 'Filling'), ('root_canal', 'Root Canal'), ('extraction', 'Extraction'), ('crown', 'Crown/Cap'), ('followup', 'Follow-up'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_steps', to='medical.appointment')),
            ],
            options={
                'ordering': ['appointment__StartTime', 'created_at'],
            },
        ),
    ]
