# Generated by Django 5.2.9 on 2026-01-06 06:50

import medical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_treatmentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=medical.models.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
