# Generated by Django 5.2.9 on 2026-01-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_patient_cin_alter_patient_insurance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='tooth_number',
        ),
        migrations.AddField(
            model_name='toothfinding',
            name='found_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_findings', to='medical.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_type',
            field=models.CharField(choices=[('AMO', 'AMO (CNSS/CNOPS)'), ('MUTUELLE', 'Mutuelle Privée'), ('MUTUELLE_FAR', 'Mutuelle Far'), ('NONE', 'Sans Assurance')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='toothfinding',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='treatmentstep',
            name='tooth_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.patient')),
            ],
        ),
    ]
