# Generated by Django 5.2.9 on 2026-01-08 08:46

import medical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_remove_appointment_tooth_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_alerts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_id',
            field=medical.models.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_type',
            field=models.CharField(choices=[('AMO', 'AMO'), ('MUTUELLE', 'Mutuelle Privée'), ('MUTUELLE_FAR', 'Mutuelle FAR'), ('NONE', 'Sans')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=medical.models.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='toothfinding',
            name='condition',
            field=models.CharField(choices=[('CARIES', 'Carie'), ('MISSING', 'Absente'), ('FILLING', 'Obturation'), ('CROWN', 'Couronne'), ('IMPLANT', 'Implant'), ('ROOT_CANAL', 'Dévitalisée')], max_length=50),
        ),
    ]
