# Generated by Django 5.2.9 on 2026-01-08 09:20

import medical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_patient_allergies_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=medical.models.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cin_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
