# Generated by Django 5.2.9 on 2026-01-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_patient_address_patient_cin_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
